
build:
  tags:
    - maven
    - docker
  script:
    - mvn clean compile

test:
  tags:
    - maven
    - docker
  script:
    - (cd acme4j-it; mvn -B docker:remove)
    - mvn -B -P ci verify

deploy:
  tags:
    - maven
    - docker
  script:
    - mvn -B install javadoc:javadoc mkdocs:build
